In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('11-naive-bayes-classification-supervised-ml-algorithm')
jovian.set_colab_id('1IUefZnjft4QV9Xwg5WO1YUhvFyEM-ZyO')

     |████████████████████████████████| 68 kB 2.5 MB/s 


# Naive Bayes Classification

![Bayes theorem](Bayestheorem_formulae.png 'Bayestheorem_formulae')

Key Points:
--
>__1. NB gives better result in multi class problems.__

And

>__2. NB gives better results when there is least colinearity among independent features.__

![NaiveBayesFormalae](naive_bayes_formulae.png 'naive_bayes_formulae')

# How Naive Bayes algorithm works?

!['Example Tables'](NaiveBayes_example_tables.png 'NaiveBayes_example_tables')

# A basic model using Naive Bayes in Python

In [2]:
# Import Library of Gaussian Naive Bayes model
# your code goes here1
from sklearn.naive_bayes import GaussianNB
import numpy as np

# assigning predictor and target variables
x = np.array([[-3,7],[1,5], [1,2], [-2,0], [2,3], 
             [-4,0], [-1,1], [1,1], [-2,2], [2,7], [-4,1], [-2,7]])
print(x,"\n\n",x.shape)
Y = np.array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4])
print("\n",Y,"\n\n",Y.shape)

[[-3  7]
 [ 1  5]
 [ 1  2]
 [-2  0]
 [ 2  3]
 [-4  0]
 [-1  1]
 [ 1  1]
 [-2  2]
 [ 2  7]
 [-4  1]
 [-2  7]] 

 (12, 2)

 [3 3 3 3 4 3 3 4 3 4 4 4] 

 (12,)


In [3]:
model = GaussianNB()

model.fit(x, Y)

predicted = model.predict([[1,2],[3,4]])
print(predicted)

[3 4]


# Where is Naive Bayes Classifier used ?

>1 Real time Prediction 

>2 Text classification / Spam Filtering 

>3 Recommendation System 

Lets analyze the titanic dataset to predict whether a person Survived or not.
--

In [4]:
# importing required libraries
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [5]:
# read the train and test dataset
train_data = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/BK_Birla/main/train-data.csv")
test_data = pd.read_csv('https://raw.githubusercontent.com/ingledarshan/BK_Birla/main/test-data.csv')

In [6]:
train_data.head()

Survived        Age     Fare  ...  Embarked_C  Embarked_Q  Embarked_S
0         0  28.500000   7.2292  ...           1           0           0
1         1  27.000000  10.5000  ...           0           0           1
2         1  29.699118  16.1000  ...           0           0           1
3         0  29.699118   0.0000  ...           0           0           1
4         0  17.000000   8.6625  ...           0           0           1

[5 rows x 25 columns]

In [7]:
test_data.head()

Survived   Age      Fare  ...  Embarked_C  Embarked_Q  Embarked_S
0         0  35.0    7.1250  ...           0           0           1
1         0  20.0    7.0500  ...           0           0           1
2         0  26.0    7.8958  ...           0           0           1
3         1  58.0  146.5208  ...           1           0           0
4         1  35.0   83.4750  ...           0           0           1

[5 rows x 25 columns]

In [8]:
train_data.shape

(712, 25)

In [9]:
test_data.shape

(179, 25)

In [10]:
train_x = train_data.drop(columns=['Survived'],axis=1)
train_y = train_data['Survived']

In [11]:
test_x = test_data.drop(columns=['Survived'],axis=1)
test_y = test_data['Survived']

In [12]:
train_x.head()

Age     Fare  Pclass_1  ...  Embarked_C  Embarked_Q  Embarked_S
0  28.500000   7.2292         0  ...           1           0           0
1  27.000000  10.5000         0  ...           0           0           1
2  29.699118  16.1000         0  ...           0           0           1
3  29.699118   0.0000         1  ...           0           0           1
4  17.000000   8.6625         0  ...           0           0           1

[5 rows x 24 columns]

In [13]:
train_y.head()

0    0
1    1
2    1
3    0
4    0
Name: Survived, dtype: int64

In [14]:
model = GaussianNB()

In [15]:
model.fit(train_x, train_y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [16]:
predict_train = model.predict(train_x)

In [17]:
predict_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,

In [18]:
accuracy_score(train_y, predict_train)

0.44803370786516855

In [21]:
predict_test = model.predict(te)

NameError: ignored

In [22]:
predict_test = model.predict(test_x)
predict_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [23]:
accuracy_score(test_y, predict_test)

0.35195530726256985

# Happy Learning